describe('MAIN_',function(){

  it('MAIN_01',function(){
      cy.visit('https://testkube.io');
  })

  it('MAIN_02',function(){
      cy.contains('Easily store and download files generated by your tests from your Kubernetes cluster')
  })
  
   it('MAIN_03',function(){
      cy.get('#start_home').click();
  })
  
})
