describe('cypress test image',function(){

  it('CTI_TS01_TC02',function(){
      cy.visit('https://testkube.io');
  })

  it('CTI_TS01_TC01',function(){
      cy.contains('Easily store and download files generated by your tests from your Kubernetes cluster')
  })
  
   it('TS_TC03',function(){
      cy.get('#start_home').click();
  })
  
})
