describe('Check content in Testkube.io',function(){

  it('Visit the URL',function(){
      cy.visit('https://testkube.io');
  })

  it('Click on Test Artifacts section',function(){
      cy.get('#w-tabs-0-data-w-tab-3').click();
  })

  it('Check section copy',function(){
      cy.contains('Easily store and download files generated by your tests from your Kubernetes cluster')
  })

}) 