

 describe('suite',function(){

  it('S_TS01_TC01',function(){
      cy.visit('https://testkube.io');
      cy.log(`Executed Successfully`);
  })

  it('S_TS01_TC02',function(){
      cy.contains('Easily store and download files generated by your tests from your Kubernetes cluster');
      cy.log(`Executed Successfully`);
  })
  
   it('S_TS01_TC03',function(){
      cy.get('#start_home').click();
      cy.log(`Executed Successfully`);
  })
  
})
